
# include <openssl/opensslv.h>
# define OPENSSL_NO_RFC3779
# define OPENSSL_NO_MD2
# define OPENSSL_NO_RC5
# define OPENSSL_THREADS
# define OPENSSL_RAND_SEED_OS
# define OPENSSL_NO_ASAN
# define OPENSSL_NO_ASM
# define OPENSSL_NO_CRYPTO_MDEBUG
# define OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE
# define OPENSSL_NO_DEVCRYPTOENG
# define OPENSSL_NO_EC_NISTP_64_GCC_128
# define OPENSSL_NO_EGD
# define OPENSSL_NO_EXTERNAL_TESTS
# define OPENSSL_NO_FUZZ_AFL
# define OPENSSL_NO_FUZZ_LIBFUZZER
# define OPENSSL_NO_HEARTBEATS
# define OPENSSL_NO_MSAN
# define OPENSSL_NO_SCTP
# define OPENSSL_NO_SSL_TRACE
# define OPENSSL_NO_SSL3
# define OPENSSL_NO_SSL3_METHOD
# define OPENSSL_NO_UBSAN
# define OPENSSL_NO_UNIT_TEST
# define OPENSSL_NO_WEAK_SSL_CIPHERS
# define OPENSSL_NO_STATIC_ENGINE
# define OPENSSL_NO_AFALGENG
# define NON_EMPTY_TRANSLATION_UNIT static void *dummy = &dummy;
# define DECLARE_DEPRECATED(f)   f __attribute__ ((deprecated));
# define OPENSSL_MIN_API 0
# define OPENSSL_API_COMPAT 0
# define DEPRECATEDIN_1_2_0(f)   f;
# define DEPRECATEDIN_1_1_0(f)   DECLARE_DEPRECATED(f)
# define DEPRECATEDIN_1_0_0(f)   DECLARE_DEPRECATED(f)
# define DEPRECATEDIN_0_9_8(f)   DECLARE_DEPRECATED(f)
# define OPENSSL_FILE __FILE__
# define OPENSSL_LINE __LINE__
# undef OPENSSL_UNISTD
# define OPENSSL_UNISTD <unistd.h>
# undef OPENSSL_EXPORT_VAR_AS_FUNCTION
# undef BN_LLONG
# undef SIXTY_FOUR_BIT_LONG
# undef SIXTY_FOUR_BIT
# undef THIRTY_TWO_BIT
# define SIXTY_FOUR_BIT
# define RC4_INT unsigned int
